### ISSUE TITLE
需要更多zookeeper特性

### ISSUE THREAD

**Issue by yydick** [Timandes/libzookeeper#14]
你好：
       我看到，你开发的zookeeper扩展里面，只有一些简单的接口，没有建立Watches，并且只有同步调用，如果你的GMAIL邮箱可用的话，我希望能够与你探讨一下这个问题。

**Comment by Timandes** [comment]
具体需要哪些呢？我这边的应用场景不是太多。

**Comment by yydick** [comment]
邮件联系。

**Comment by joostshao** [comment]
这个issue可以保持开放，持续关注
