### ISSUE TITLE
如何在windows环境中安装php-zookeeper扩展

### ISSUE THREAD

**Issue by niyaode** [Timandes/libzookeeper#22]

**Comment by Timandes** [comment]
这个目前没有办法呀，我对Windows下编程不太熟悉。
原理上来看，应该先将Zookeeper C Client编译成mt_zookeeper.lib。然后再将他并入php-zookeeper编译成zookeeper.dll。
顺便说一句：这个项目不是php-zookeeper。
正主在https://github.com/php-zookeeper/php-zookeeper
